# Generated by Django 6.0.7 on 2026-07-20 10:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.CharField(blank=True, max_length=100, null=True)),
                ('completion_time', models.CharField(blank=True, max_length=100, null=True)),
                ('submission_date', models.DateField(blank=True, null=True)),
                ('employer_code', models.CharField(max_length=100)),
                ('employer_name', models.CharField(max_length=255)),
                ('primary_sector', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('block', models.CharField(max_length=100)),
                ('riico_area', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField()),
                ('organisation_type', models.CharField(max_length=100)),
                ('product_service_type', models.CharField(max_length=50)),
                ('company_size', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('active_status', models.CharField(default='Yes', max_length=10)),
                ('senior_official_name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[6-9][0-9]{9}$', 'Enter a valid 10 digit Indian mobile number.')])),
                ('email_id', models.EmailField(max_length=254)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('hr_mobile_number', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^[6-9][0-9]{9}$', 'Enter a valid 10 digit Indian mobile number.')])),
                ('placement_ready', models.CharField(default='Yes', max_length=10)),
                ('apprenticeship_ready', models.CharField(default='Yes', max_length=10)),
                ('guest_lecture_ready', models.CharField(default='Yes', max_length=10)),
                ('exposure_visit_ready', models.CharField(default='Yes', max_length=10)),
                ('csr_interest', models.CharField(default='Yes', max_length=10)),
                ('awareness_of_rsldc', models.CharField(default='Yes', max_length=10)),
                ('local_employee_ready', models.CharField(default='Yes', max_length=10)),
                ('collaboration_ready', models.CharField(default='Yes', max_length=10)),
                ('hiring_challenges', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'survey_surveys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_no', models.IntegerField(default=1)),
                ('sector', models.CharField(max_length=100)),
                ('job_role', models.CharField(max_length=255)),
                ('education_req', models.CharField(max_length=100)),
                ('experience_req', models.CharField(max_length=50)),
                ('salary_expected', models.CharField(max_length=50)),
                ('current_demand', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('future_demand', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('demand_6_months', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('demand_12_months', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('apprenticeship_demand', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('placement_demand', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_demands', to='demand.survey')),
            ],
            options={
                'db_table': 'survey_job_demands',
                'ordering': ['row_no'],
            },
        ),
    ]
