# Generated by Django 5.0.6 on 2026-08-13 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('start_time', models.CharField(blank=True, max_length=100, null=True)),
                ('completion_time', models.CharField(blank=True, max_length=100, null=True)),
                ('submission_date', models.DateField(auto_now_add=True, null=True)),
                ('field_officer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('field_officer_signature', models.CharField(blank=True, max_length=255, null=True)),
                ('company_name', models.CharField(max_length=255)),
                ('organisation_type', models.CharField(max_length=100)),
                ('organisation_type_other', models.CharField(blank=True, max_length=100, null=True)),
                ('product_service', models.CharField(max_length=50)),
                ('product_service_specify', models.CharField(blank=True, max_length=255, null=True)),
                ('operational_sector', models.CharField(max_length=100)),
                ('operational_sector_other', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField()),
                ('website', models.URLField(blank=True, max_length=500, null=True)),
                ('district', models.CharField(max_length=100)),
                ('block', models.CharField(max_length=100)),
                ('contact_name', models.CharField(max_length=255)),
                ('contact_mobile', models.CharField(max_length=10)),
                ('contact_email', models.EmailField(max_length=254)),
                ('workforce_profile', models.JSONField(blank=True, default=list, null=True)),
                ('placement_willingness', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10)),
                ('apprenticeship_willingness', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10)),
                ('guest_lecture_interest', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10)),
                ('industrial_visit_interest', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10)),
                ('csr_interest', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10)),
                ('ojt_internship_willingness', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10)),
                ('recruitment_challenges', models.TextField(blank=True, null=True)),
                ('additional_remarks', models.TextField(blank=True, null=True)),
                ('supporting_evidence', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Survey',
                'verbose_name_plural': 'Surveys',
                'db_table': 'survey_surveys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_no', models.IntegerField(default=1)),
                ('job_role', models.CharField(max_length=255)),
                ('sector', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('qualification_other', models.CharField(blank=True, max_length=100, null=True)),
                ('experience', models.CharField(max_length=50)),
                ('certification', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10)),
                ('certification_detail', models.CharField(blank=True, max_length=255, null=True)),
                ('salary_offered', models.CharField(max_length=50)),
                ('current_openings', models.IntegerField(default=0)),
                ('openings_6_months', models.IntegerField(default=0)),
                ('openings_12_months', models.IntegerField(default=0)),
                ('apprentice_ojt', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10)),
                ('apprentice_ojt_detail', models.CharField(blank=True, max_length=255, null=True)),
                ('gender_suitability', models.CharField(default='Any / No Preference', max_length=50)),
                ('pwd', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('NA', 'NA')], default='NA', max_length=10)),
                ('additional_remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_demands', to='demand.survey')),
            ],
            options={
                'verbose_name': 'Job Demand',
                'verbose_name_plural': 'Job Demands',
                'db_table': 'survey_job_demands',
                'ordering': ['survey', 'row_no'],
            },
        ),
        migrations.CreateModel(
            name='ApprenticeshipOJT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_no', models.IntegerField(default=1)),
                ('job_role', models.CharField(max_length=255)),
                ('opportunity_type', models.CharField(choices=[('Apprenticeship', 'Apprenticeship'), ('OJT', 'OJT'), ('Internship', 'Internship')], max_length=50)),
                ('seats_capacity', models.IntegerField(default=0)),
                ('duration_months', models.IntegerField(default=0)),
                ('monthly_stipend', models.IntegerField(default=0)),
                ('expected_start_month', models.CharField(blank=True, max_length=50, null=True)),
                ('minimum_qualification', models.CharField(max_length=100)),
                ('minimum_qualification_other', models.CharField(blank=True, max_length=100, null=True)),
                ('conversion_to_employment', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apprenticeships', to='demand.survey')),
            ],
            options={
                'verbose_name': 'Apprenticeship/OJT',
                'verbose_name_plural': 'Apprenticeships/OJTs',
                'db_table': 'survey_apprenticeships',
                'ordering': ['survey', 'row_no'],
            },
        ),
    ]
