# Generated by Django 6.0.7 on 2026-07-21 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobdemand',
            options={'ordering': ['survey', 'row_no'], 'verbose_name': 'Job Demand', 'verbose_name_plural': 'Job Demands'},
        ),
        migrations.AlterModelOptions(
            name='survey',
            options={'ordering': ['-created_at'], 'verbose_name': 'Survey', 'verbose_name_plural': 'Surveys'},
        ),
        migrations.AlterField(
            model_name='jobdemand',
            name='apprenticeship_demand',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jobdemand',
            name='current_demand',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jobdemand',
            name='demand_12_months',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jobdemand',
            name='demand_6_months',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jobdemand',
            name='future_demand',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jobdemand',
            name='placement_demand',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='survey',
            name='active_status',
            field=models.CharField(blank=True, default='Yes', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='apprenticeship_ready',
            field=models.CharField(blank=True, default='Yes', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='awareness_of_rsldc',
            field=models.CharField(blank=True, default='Yes', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='collaboration_ready',
            field=models.CharField(blank=True, default='Yes', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='company_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='survey',
            name='csr_interest',
            field=models.CharField(blank=True, default='Yes', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='exposure_visit_ready',
            field=models.CharField(blank=True, default='Yes', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='guest_lecture_ready',
            field=models.CharField(blank=True, default='Yes', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='hr_mobile_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='local_employee_ready',
            field=models.CharField(blank=True, default='Yes', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='mobile_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='survey',
            name='placement_ready',
            field=models.CharField(blank=True, default='Yes', max_length=10, null=True),
        ),
    ]
