# Generated by Django 5.0.6 on 2026-08-24 11:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='supporting_document',
            field=models.FileField(blank=True, help_text='Upload PDF or Image (Max 50KB)', null=True, upload_to='supporting_documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'gif', 'bmp'])]),
        ),
    ]
