# Generated by Django 5.0.6 on 2026-08-07 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0002_alter_jobdemand_options_alter_survey_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='email',
            new_name='respondent_email',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='hr_mobile_number',
            new_name='respondent_mobile',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='name',
            new_name='respondent_name',
        ),
        migrations.AddField(
            model_name='jobdemand',
            name='certification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobdemand',
            name='gender_suitability',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='mode_of_interview',
            field=models.CharField(blank=True, choices=[('Field Visit', 'Field Visit'), ('Telephonic', 'Telephonic')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='nature_of_operations',
            field=models.CharField(blank=True, choices=[('Year-round', 'Year-round'), ('Seasonal', 'Seasonal'), ('Project-Based', 'Project-Based'), ('Mixed', 'Mixed')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='on_the_job_training_ready',
            field=models.CharField(blank=True, default='No', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='organisation_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='supporting_evidence',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='ApprenticeshipOJT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_no', models.IntegerField(default=1)),
                ('job_role', models.CharField(max_length=255)),
                ('opportunity_type', models.CharField(choices=[('Apprenticeship', 'Apprenticeship'), ('OJT', 'OJT'), ('Internship', 'Internship')], max_length=50)),
                ('seats_capacity', models.IntegerField(default=0)),
                ('duration_months', models.IntegerField(default=0)),
                ('monthly_stipend', models.IntegerField(default=0)),
                ('expected_start_month', models.CharField(blank=True, max_length=50, null=True)),
                ('minimum_qualification', models.CharField(blank=True, max_length=100, null=True)),
                ('employment_conversion', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apprenticeships', to='demand.survey')),
            ],
            options={
                'verbose_name': 'Apprenticeship/OJT',
                'verbose_name_plural': 'Apprenticeships/OJTs',
                'db_table': 'survey_apprenticeships',
                'ordering': ['survey', 'row_no'],
            },
        ),
    ]
