# Generated by Django 5.0.6 on 2026-09-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0002_survey_supporting_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdemand',
            name='career_next_position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobdemand',
            name='career_next_salary',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobdemand',
            name='career_progression',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
        migrations.AddField(
            model_name='jobdemand',
            name='career_progression_years',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='company_size',
            field=models.CharField(blank=True, choices=[('Micro', 'Micro'), ('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='has_hr',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
    ]
