# Generated by Django 5.0.6 on 2026-08-11 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0003_rename_email_survey_respondent_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobdemand',
            old_name='apprenticeship_demand',
            new_name='current_openings',
        ),
        migrations.RenameField(
            model_name='jobdemand',
            old_name='experience_req',
            new_name='experience',
        ),
        migrations.RenameField(
            model_name='jobdemand',
            old_name='current_demand',
            new_name='openings_12_months',
        ),
        migrations.RenameField(
            model_name='jobdemand',
            old_name='demand_12_months',
            new_name='openings_6_months',
        ),
        migrations.RenameField(
            model_name='jobdemand',
            old_name='education_req',
            new_name='qualification',
        ),
        migrations.RenameField(
            model_name='jobdemand',
            old_name='salary_expected',
            new_name='salary_offered',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='remarks',
            new_name='additional_remarks',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='employer_name',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='email_id',
            new_name='contact_email',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='mobile_number',
            new_name='contact_mobile',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='senior_official_name',
            new_name='contact_name',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='hiring_challenges',
            new_name='field_officer_name',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='respondent_name',
            new_name='field_officer_signature',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='employer_code',
            new_name='operational_sector',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='product_service_type',
            new_name='product_service',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='riico_area',
            new_name='product_service_specify',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='organisation_url',
            new_name='website',
        ),
        migrations.RemoveField(
            model_name='apprenticeshipojt',
            name='employment_conversion',
        ),
        migrations.RemoveField(
            model_name='jobdemand',
            name='demand_6_months',
        ),
        migrations.RemoveField(
            model_name='jobdemand',
            name='future_demand',
        ),
        migrations.RemoveField(
            model_name='jobdemand',
            name='placement_demand',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='active_status',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='apprenticeship_ready',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='awareness_of_rsldc',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='collaboration_ready',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='company_size',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='exposure_visit_ready',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='guest_lecture_ready',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='local_employee_ready',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='mode_of_interview',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='nature_of_operations',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='on_the_job_training_ready',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='placement_ready',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='primary_sector',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='respondent_email',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='respondent_mobile',
        ),
        migrations.AddField(
            model_name='apprenticeshipojt',
            name='conversion_to_employment',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='apprenticeshipojt',
            name='minimum_qualification_other',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobdemand',
            name='additional_remarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobdemand',
            name='apprentice_ojt',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='jobdemand',
            name='apprentice_ojt_detail',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobdemand',
            name='certification_detail',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobdemand',
            name='pwd',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('NA', 'NA')], default='NA', max_length=10),
        ),
        migrations.AddField(
            model_name='jobdemand',
            name='qualification_other',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='apprenticeship_willingness',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='survey',
            name='company_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='guest_lecture_interest',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='survey',
            name='industrial_visit_interest',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='survey',
            name='ojt_internship_willingness',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='survey',
            name='operational_sector_other',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='organisation_type_other',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='placement_willingness',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='survey',
            name='recruitment_challenges',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='workforce_profile',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apprenticeshipojt',
            name='minimum_qualification',
            field=models.CharField(default='10th Pass', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobdemand',
            name='certification',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10),
        ),
        migrations.AlterField(
            model_name='jobdemand',
            name='gender_suitability',
            field=models.CharField(default='Any / No Preference', max_length=50),
        ),
        migrations.AlterField(
            model_name='survey',
            name='csr_interest',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10),
        ),
    ]
