# Generated by Django 5.0.6 on 2026-09-16 11:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0004_associationconsultation_associationapprenticeship_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovtConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('district_region', models.CharField(max_length=255)),
                ('mode', models.CharField(choices=[('In-person', 'In-person'), ('Telephone', 'Telephone'), ('Video Call', 'Video Call'), ('Written Submission', 'Written Submission'), ('Other', 'Other')], max_length=50)),
                ('mode_other', models.CharField(blank=True, max_length=100, null=True)),
                ('consultation_date', models.DateField()),
                ('surveyor_name', models.CharField(max_length=255)),
                ('office_visited', models.JSONField(blank=True, default=list, null=True)),
                ('office_visited_other', models.CharField(blank=True, max_length=255, null=True)),
                ('body_type', models.JSONField(blank=True, default=list, null=True)),
                ('body_type_other', models.CharField(blank=True, max_length=255, null=True)),
                ('jurisdiction', models.JSONField(blank=True, default=list, null=True)),
                ('jurisdiction_other', models.CharField(blank=True, max_length=255, null=True)),
                ('respondent_name', models.CharField(max_length=255)),
                ('respondent_mobile', models.CharField(max_length=10)),
                ('respondent_email', models.EmailField(max_length=254)),
                ('office_address', models.CharField(blank=True, max_length=500, null=True)),
                ('department_website', models.URLField(blank=True, max_length=500, null=True)),
                ('nodal_officer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('nodal_officer_mobile', models.CharField(blank=True, max_length=10, null=True)),
                ('nodal_officer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('investment_pipeline', models.JSONField(blank=True, default=list, null=True)),
                ('sectoral_analysis', models.JSONField(blank=True, default=list, null=True)),
                ('occupational_categories', models.JSONField(blank=True, default=list, null=True)),
                ('upcoming_schemes', models.TextField(blank=True, null=True)),
                ('emerging_technologies', models.TextField(blank=True, null=True)),
                ('aware_establishments', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Not Sure', 'Not Sure')], max_length=20, null=True)),
                ('can_facilitate', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Conditional', 'Conditional')], max_length=20, null=True)),
                ('aware_establishments_count', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('concentration_sectors', models.CharField(blank=True, max_length=500, null=True)),
                ('known_employers', models.CharField(blank=True, max_length=500, null=True)),
                ('facilitation_mode', models.JSONField(blank=True, default=list, null=True)),
                ('recruitment_challenges', models.JSONField(blank=True, default=list, null=True)),
                ('difficult_roles', models.CharField(blank=True, max_length=500, null=True)),
                ('emerging_roles', models.CharField(blank=True, max_length=500, null=True)),
                ('changing_competencies', models.CharField(blank=True, max_length=500, null=True)),
                ('skill_gaps', models.CharField(blank=True, max_length=500, null=True)),
                ('high_demand_districts', models.CharField(blank=True, max_length=500, null=True)),
                ('unfilled_reasons', models.CharField(blank=True, max_length=500, null=True)),
                ('operational_challenges', models.TextField(blank=True, null=True)),
                ('facilitate_surveys', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Conditional', 'Conditional')], max_length=20, null=True)),
                ('share_registration_data', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Conditional', 'Conditional')], max_length=20, null=True)),
                ('participate_coordination', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Conditional', 'Conditional')], max_length=20, null=True)),
                ('share_demand_updates', models.CharField(blank=True, choices=[('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Half-yearly', 'Half-yearly'), ('As required', 'As required'), ('Not feasible', 'Not feasible')], max_length=50, null=True)),
                ('dept_nodal_officer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('dept_nodal_officer_mobile', models.CharField(blank=True, max_length=10, null=True)),
                ('dept_nodal_officer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('supporting_evidence', models.JSONField(blank=True, default=list, null=True)),
                ('demand_evidence_status', models.CharField(blank=True, choices=[('Department Data Available', 'Department Data Available'), ('Aggregate / Estimated Only', 'Aggregate / Estimated Only'), ('Directional / Expert View', 'Directional / Expert View')], max_length=50, null=True)),
                ('submission_date', models.DateField(blank=True, null=True)),
                ('place', models.CharField(blank=True, max_length=255, null=True)),
                ('authorized_signature', models.CharField(blank=True, max_length=255, null=True)),
                ('respondent_signature', models.CharField(blank=True, max_length=255, null=True)),
                ('official_stamp', models.BooleanField(default=False)),
                ('supporting_document', models.FileField(blank=True, help_text='Upload PDF or Image (Max 50KB)', null=True, upload_to='govt_documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'gif', 'bmp'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Government Consultation',
                'verbose_name_plural': 'Government Consultations',
                'db_table': 'govt_consultations',
                'ordering': ['-created_at'],
            },
        ),
    ]
